### ISSUE TITLE
Spike - Import of class names

### ISSUE THREAD

**Issue by anu13297** [aemsites/esri#123]
Can we carry over the class names on div's when importing pages so it helps to style them?

**Comment by alexcarol** [comment]
That's not really possible, we can carry over class names on blocks and sections, but not generically for everything. We also agreed with @tim-white-esri that we'd try to simplify as much as possible and avoid bringing unnecessary class names (e.g. if a block is always used with a certain class we don't need to add the class)

**Comment by alexcarol** [comment]
One example that we've applied is with theming, in many cases blocks have "dark mode" applied directly, but for the import we have a list of pages with "dark" or "light" mode, so that we don't need to repeat that for each block (though that's still possible to apply ad-hoc when needed)

**Comment by alexcarol** [comment]
Modes are imported
