### ISSUE TITLE
Initial import

### ISSUE THREAD

**Issue by alexcarol** [aemsites/esri#2]
Do a first import based on the url list provided by the customer

[URls (1).xlsx](https://github.com/user-attachments/files/16230936/URls.1.xlsx)

**Comment by stefanalex99** [comment]
imported URLs https://adobe.sharepoint.com/sites/HelixProjects/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FHelixProjects%2FShared%20Documents%2Fsites%2Fesri%2Fen%2Dus&viewid=124ad5f1%2D60ba%2D476c%2Dade8%2D7c1df274ee95
