### ISSUE TITLE
Implement "cards" component

### ISSUE THREAD

**Issue by alexcarol** [aemsites/esri#20]
Original: https://www.esri.com/en-us/about/about-esri/overview
New: https://main--esri--aemsites.hlx.page/en-us/about/about-esri/overview

There's already a block for this in the boilerplate, the task is add the necessary css to "cards.css" to make it work, or use "calcite card" instead if that's the path we're looking to go.

![image](https://github.com/user-attachments/assets/2a364705-ecc8-4426-a5db-34bd20aa8549)

**Comment by alexcarol** [comment]
@tim-white-esri can you comment on this? Should we use calcite cards for this, or just build it based on the boilerplate cards?

**Comment by tim-white-esri** [comment]
I'm fine with boilerplate cards

**Comment by alexcarol** [comment]
While we could style columns like that, those look more like cards than columns to me (anything with a border like that is more a card than a column to me).
![image](https://github.com/user-attachments/assets/4e27ba45-c37c-4e73-b9a7-b1e3dda0c45f)

**Comment by tim-white-esri** [comment]
Oh, I was looking at the split just above that. 

Can we tackle it with the standard Block Card?
