### ISSUE TITLE
Add general styles to the site

### ISSUE THREAD

**Issue by alexcarol** [aemsites/esri#4]
- Identify breakpoints for different sizes (we'll want to make mobile the default)
- Add default font sizes and font files (both for the body and different heading elements)
- Add default inter-section margins
- See if there's anything else worth reusing

Some pages worth looking at:
- https://www.esri.com/en-us/about/about-esri/europe/overview
- https://www.esri.com/en-us/capabilities/imagery-remote-sensing/capabilities/management
- https://www.esri.com/en-us/digital-transformation/overview

**Comment by tim-white-esri** [comment]
@alexcarol the current breakpoints are

- large:       1440px;
- portrait:    1152px;
- tablet:      768px;
- phone:       476px;

Note: we tend to use those are guideposts, not hard and fast rules.

**Comment by tim-white-esri** [comment]
We also have a design library we make some use of called Calcite Components. It would be nice to know how we can use those custom components. 

https://developers.arcgis.com/calcite-design-system/components/
