### ISSUE TITLE
Implement Cards Simple

### ISSUE THREAD

**Issue by anu13297** [aemsites/esri#64]
Original: https://www.esri.com/en-us/digital-twin/overview
New: https://main--esri--aemsites.hlx.page/en-us/digital-twin/overview

Implement 'Cards Simple' version of cards component.

**Comment by alexcarol** [comment]
Which variant is that, is it this?
![image](https://github.com/user-attachments/assets/439aa4dc-922b-408b-9035-65fd7da4a1a9)

**Comment by anu13297** [comment]
Yes. That's the one. We have multiple other card variants as well.

**Comment by alexcarol** [comment]
For this variant and others, are you able to "detect" them based on their content structure, or will you be using a variant (changing the docs to `Cards (simple)` or similar). Preferably it would be the former when possible, but if it's the latter let's discuss how we can detect them at import time.
