### ISSUE TITLE
Localized version of page should load the correct header

### ISSUE THREAD

**Issue by alexcarol** [aemsites/esri#94]
It's currently loading the header in english.

Page: https://main--esri--aemsites.hlx.page/ja-jp/about/about-esri/overview
Live site: https://www.esri.com/ja-jp/about/about-esri/overview

**Comment by tim-white-esri** [comment]
Each language needs its own JSON file.

**Comment by tim-white-esri** [comment]
Going to see if we can solve the CORS issue on this end.

**Comment by tim-white-esri** [comment]
Current HTML is also missing `<link rel="alternate" href="https://www.esri.com/[la-la]/home" hreflang="[la-la">`
where `[la-la]` is the four character language code. For the sample page, `ja-jp` needs to be added. This is one of the triggers for global nav language selection.

**Comment by alexcarol** [comment]
The data on which urls exist can be obtained from the query index: https://main--esri--aemsites.hlx.page/query-index.json.
The recommended way to query it is using this script: https://github.com/buuhuu/ffetch/blob/main/src/ffetch.js (just copy ffetch.js to /scripts/.

**Comment by twhite313** [comment]
Partially resolved with issue #132 

@alexcarol I might need a bit of guidance on how to use this.

**Comment by alexcarol** [comment]
You can get the results with this:
```
  const data = await ffetch('/query-index.json').all();
```
