### ISSUE TITLE
Map block should have 90+ lighthouse scroe

### ISSUE THREAD

**Issue by hanem100k** [aemsites/esri#96]
Currently, even though we're loading our iframe lazily, it blocks on load, reducing our LS score to low sixties.

Todo. Add background loading and only block while the placeholder is  loading.

The placeholder could be an image of a loaded map, or just text, if the eventual load is fast.

**Comment by tim-white-esri** [comment]
We use Intersection Observer for some lazy loading. 
You could not load it until it reaches the viewport. No need to load the map at all if the user isn't scrolling down. 

Certainly something we can test. @jsavella you've worked with Felipe on our lazy loading correct?

**Comment by tim-white-esri** [comment]
I see. I was looking at the full page, not the isolated test. 

A placeholder is fine. We have the Calcite framework loaded so you should be able to leverage the Calcite Loader, which might be an option:

`<calcite-loader label="Loading map..."></calcite-loader>`
https://developers.arcgis.com/calcite-design-system/components/loader/
