### ISSUE TITLE
Map iframe should be hosted as own assets

### ISSUE THREAD

**Issue by hanem100k** [aemsites/esri#97]
Loading an iframe loads a new document.

In order to be able to display this document full screen, we need to augment its height property.

Because these documents are hosted on esri CDN, we cannot mutate the attributes.

TODO.

Modify the iframe on esri CDN to have relative height.

OR

Host these frames inside our own SharePoint so we can customize them further.

**Comment by tim-white-esri** [comment]
We can skip the full screen option for now. 

We can update the map itself to include the feature. Or in the future we can create a new element to natively embed maps on the page. That requires more work that I think is outside of the scope for now.

**Comment by hanem100k** [comment]
We can skip the full screen option for now.

@tim-white-esri sounds good. Removing the button then and closing the issue.
